name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
#  pull_request:
#    types: [opened, synchronize, reopened, closed]
#    branches:
#      - main

jobs:
  build_job:
    runs-on: windows-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install DocFX
        run: dotnet tool update -g docfx
        env:
          CI: true
      - name: build documentation
        run: |
          docfx build --warningsAsErrors
      - name: publish results
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: _site/
